# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a235e1dc38bb48cfb32ff98af83c9ffb8922906bec1ba9f07068365e741e54b38065551fb31d35bcebb657845a5d716e613f507b0a166b3d2c664e1182f53bbd

test:
  secret_key_base: 50fd90fa777c6d35ba1909ac8022905e3006fa72c67a3646bfed5a3f33bded2b49037796534b1e9f806dbd3f4ac68d42e39a20110b9821130c35ae22027801f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
